title: "Мое резюме"  # Замените на ваш заголовок
description: "Персональное резюме и портфолио"  # Замените на описание
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
