title: "Мое резюме"  # Замените на ваш заголовок
description: "Персональное резюме и портфолио"  # Замените на описание
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false  # Уберите, если нужны кнопки скачивания
