openapi: 3.0.0
info:
  title: Product Catalog API
  version: 1.0.0
  description: API для управления каталогом товаров

paths:
  /api/products:
    get:
      summary: Получить список товаров
      tags:
        - Products
      operationId: getProducts
      parameters:
        - name: category
          in: query
          description: ID категории для фильтрации
          schema:
            type: integer
        - name: price_min
          in: query
          description: Минимальная цена
          schema:
            type: number
            minimum: 0
        - name: price_max
          in: query
          description: Максимальная цена
          schema:
            type: number
            minimum: 0
        - name: sort
          in: query
          description: Поле для сортировки
          schema:
            type: string
            enum: [price, rating, popularity]
        - name: order
          in: query
          description: Направление сортировки
          schema:
            type: string
            enum: [asc, desc]
        - name: limit
          in: query
          description: Лимит товаров
          schema:
            type: integer
            minimum: 10
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Смещение
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Ошибки валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Создать новый товар
      tags:
        - Products
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: Товар создан успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Ошибки валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/products/{id}:
    get:
      summary: Получить товар по ID
      tags:
        - Products
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Обновить товар
      tags:
        - Products
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
      responses:
        '200':
          description: Товар обновлен успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Ошибки валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Удалить товар
      tags:
        - Products
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Товар удален успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteProductResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateProductRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            name:
              type: string
              minLength: 1
              maxLength: 255
              description: Название товара
            description:
              type: string
              maxLength: 3000
              description: Описание товара
            price:
              type: number
              minimum: 0
              description: Цена товара
            currency:
              type: string
              enum: [USD, EUR, RUB]
              default: RUB
              description: Валюта цены
            category_id:
              type: integer
              description: ID категории
            images:
              type: array
              items:
                type: string
                format: uri
              description: Ссылки на изображения
          required:
            - name
            - price
            - category_id

    UpdateProductRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            name:
              type: string
              minLength: 1
              maxLength: 255
              description: Название товара
            description:
              type: string
              maxLength: 3000
              description: Описание товара
            price:
              type: number
              minimum: 0
              description: Цена товара
            currency:
              type: string
              enum: [USD, EUR, RUB]
              description: Валюта цены
            in_stock:
              type: boolean
              description: Наличие товара
            images:
              type: array
              items:
                type: string
                format: uri
              description: Ссылки на изображения

    Product:
      type: object
      properties:
        id:
          type: integer
          description: ID товара
        name:
          type: string
          description: Название товара
        description:
          type: string
          description: Описание товара
        price:
          type: number
          description: Цена товара
        currency:
          type: string
          description: Валюта цены
        rating:
          type: number
          minimum: 0
          maximum: 5
          description: Рейтинг товара
        in_stock:
          type: boolean
          description: Наличие товара
        images:
          type: array
          items:
            type: string
            format: uri
          description: Ссылки на изображения
        created_at:
          type: string
          format: date-time
          description: Дата создания
        updated_at:
          type: string
          format: date-time
          description: Дата обновления

    ProductsResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            products:
              type: array
              items:
                $ref: '#/components/schemas/Product'
            meta:
              type: object
              properties:
                total:
                  type: integer
                  description: Общее количество товаров
                limit:
                  type: integer
                  description: Лимит товаров
                offset:
                  type: integer
                  description: Смещение

    ProductResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/Product'

    CreateProductResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            id:
              type: integer
              description: ID созданного товара

    DeleteProductResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            id:
              type: integer
              description: ID удаленного товара

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              description: Код ошибки
            message:
              type: string
              description: Сообщение об ошибке
            details:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: Поле с ошибкой
                  message:
                    type: string
                    description: Сообщение об ошибке
